import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '../globals.css'
import Footer from "./components/Footer";
import Header from "./components/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "FPM",
    description: "Generated by create next app",
    icons: {
        icon: "/panel/favicon.ico", // مسیر favicon در پوشه public
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col min-h-screen bg-gray-200 text-gray-800 h-screen">
            <Header />
            {children}
            <Footer />
        </div>
    );
}
