// src/app/layout.js

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';

// تنظیم فونت‌ها
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// تنظیم متادیتا و آیکون‌ها
export const metadata: Metadata = {
  title: "FPM",
  description: "Generated by create next app",
  icons: {
    // مسیر صحیح برای فایل favicon
    // فایل را مستقیماً در پوشه public قرار دهید.
    // در این صورت، کد زیر به صورت خودکار کار خواهد کرد.
    icon: "/panel/favicon.ico", 
  },
};

// کامپوننت اصلی Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
